### ISSUE TITLE
Consider min/max constraints as well in the inferred spec

### ISSUE THREAD

**Issue by anujsrc** [stathissideris/spec-provider#11]
Currently, spec-provider captures the stats correctly for each number, like- min/max, etc. but does not consider the same while generating the spec. It would be good to provide an option to impose the same on the generated spec by default. As of now, you need to define it explicitly and then merge with the existing spec that is one added step for the users.

**Comment by stathissideris** [comment]
This is now implemented in 0.4.9

**Comment by anujsrc** [comment]
Thanks @stathissideris - I will try it out
