### ISSUE TITLE
bigdec?  has been removed from Clojure 1.9.0

### ISSUE THREAD

**Issue by linpengcheng** [stathissideris/spec-provider#18]
bigdec?  has been removed from Clojure 1.9.0

**Comment by stathissideris** [comment]
Thanks, I noticed that myself, will fix ASAP.

**Comment by linpengcheng** [comment]
Thanks, spec-provider is an excellent project.

**Comment by stathissideris** [comment]
👍  :-)

**Comment by stathissideris** [comment]
This is now fixed in 0.4.11
